### ISSUE TITLE
Dataset used for training the model

### ISSUE THREAD

**Issue by krithravi** [vagarwal87/saluki_paper#1]
Hi! I was looking into reproducing the saluki model! Would you be able to link me to the datasets used to train the model? I've looked through the datasets provided in the supplementary information as well as looked around the basenji repo, but I can't seem to find that. Thank you!

**Comment by vagarwal87** [comment]
Hi. Thanks for your interest. Please read the README of this repo in detail as it provides the Zenodo link of all of the data.

**Comment by krithravi** [comment]
Thank you! Sorry for the trouble!

**Comment by vagarwal87** [comment]
No problem, good luck!

**Comment by krithravi** [comment]
HI! I had another question - I was looking inside the datasets directory, and there are subdirectories within the GRU directory such as f1_c1 and so on - what do these these represent? Also, there is a data0 and data1 subdirectories which each one of the fX_cX directories - what would these represent? Thank you!

**Comment by vagarwal87** [comment]
Hi, great question! f{0-9} alludes to the 10 folds of data; c{0-4} is the 5 trials in which the model is trained independently from scratch. data0=data from human; data1=data from mouse. There are examples in my saluki_paper github demonstrating the deployment of all 50 models, and averaging the results, to get a more precise prediction. Hope that helps!
