### ISSUE TITLE
Pipeline overview

### ISSUE THREAD

**Issue by crj0139** [vagarwal87/saluki_paper#11]
Hello,

  I am trying to determine where in the entire pipeline I can put my own data in, but am having trouble figuring out exactly which part of the basenji and saluki_paper repos to use.  I have a list of sequences I want to get predictions for, but I also want to train my own model.

  Are the saluki_.py scripts all that are needed to run the actual pipeline?  It seems like most things in saluki_paper are just for recreating the figures, but not fully showing the pipeline in one place.

Cheers

**Comment by vagarwal87** [comment]
Hi, this repo was primarily written to reproduce the figures. It contains scripts to use pretrained models to generate predictions for each of the figure panels. If you would like to retrain your own model, the baseji repo with saluki scripts are more appropriate. Unfortunately we didn't have time to merge all of the pipeline in one place. All of the models are available via zenodo in case you'd like to fine tune them further as well.

**Comment by crj0139** [comment]
Got it; I have the Zenodo stuff downloaded and will just focus on that with the saluki.py scripts in the basenji repo.  Thank you!
