### ISSUE TITLE
Error in running generate_training_input.pl

### ISSUE THREAD

**Issue by tongshiyuan** [vagarwal87/saluki_paper#2]
hi,  
Thanks for you script, and that is very informative.  
but when I running the script `generate_training_input.pl` in `Fig3_S4`, I found the error like 
~~~
Can't locate allfxns.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./generate_training_input.pl line 3.
BEGIN failed--compilation aborted at ./generate_training_input.pl line 3.
~~~
How can I get the `allfxns.pm` file? I want to generate other genes features by `generate_training_input.pl`.
Thank you very much for your time, I look forward to hearing from you.
Warmest regards, 
Tong

**Comment by vagarwal87** [comment]
Thanks for pointing this out Tong. This particular script is one I originally wrote in Xpresso and was a Perl module that helps calculate GC content, etc. It can be found here:

https://github.com/vagarwal87/Xpresso/blob/master/allfxns.pm
