### ISSUE TITLE
FigS3.R code missing from Fig2_S3 dir

### ISSUE THREAD

**Issue by QuantumAlmonds** [vagarwal87/saluki_paper#3]
Hi, was wondering if there was an R script for Fig S3 that you could add to the repo. I couldn't find it in the expected place. Thanks!

**Comment by vagarwal87** [comment]
https://github.com/vagarwal87/saluki_paper/blob/main/Fig2_S3/Fig2abc_S3.R hi this code was used to generate that and it includes a comment at the end with instructions on how S3 was generated.

**Comment by QuantumAlmonds** [comment]
Thanks for the quick reply, sorry about the confusion. :)
