### ISSUE TITLE
How to understand the final predictions?

### ISSUE THREAD

**Issue by Jojo-LIU-LIU** [vagarwal87/saluki_paper#8]
Hi, Vikram! Now, I obtain the final predictions of a series of 3' UTRs with a fixed 5'UTR+ORF by calculating the mean of 50 predicitons. They are all negative values. I have some little questions as following:
1), The larger the value, the longer the half-life, right? I set the 3'UTR with the largest predicted value of corresponding mRNA as best 3'UTR, am I right?
2), Could I directly calculate a correlation coefficient between predicted and observed values? Is it necessary to replace the predicted values with deviations from the mean value across all 3' UTRs? How to deal with the observed values?
Looking foward you reply! Thanks!

**Comment by vagarwal87** [comment]
1) yes, correct
2) yes, if you have data for it, then sure you can calculate corr. between obs vs pred values (shown many times in the paper when using fastUTR assay, MPRA, etc.).
